workers: 8
sourceDS: !!org.apache.commons.dbcp2.BasicDataSource
  url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
  username: app
  password: app

targetDS: !!org.apache.commons.dbcp2.BasicDataSource
  url: jdbc:mysql://127.0.0.1:3306/shard?autoReconnect=true&useCursorFetch=true&cacheServerConfiguration=true&useLocalSessionState=true&elideSetAutoCommits=true&connectTimeout=3000&socketTimeout=60000&useSSL=false&useAffectedRows=true&cacheCallableStmts=true&noAccessToProcedureBodies=true&characterEncoding=utf8&characterSetResults=utf8&connectionCollation=utf8_bin
  username: shard
  password: shard
  maxTotal: 30
  maxWaitMillis: 100
  validationQuery: SELECT 1
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis : 1200000
  numTestsPerEvictionRun : 10

retryCount: 10
retryMili: 5000
batchCount: 300
insertIgnore: false
partitionKey: name

exportQuery: "select * from T_USER"

upsert: true
targetTables:
- name: "MY_USER"
  deleteQuery: "delete from MY_USER limit 10000"