workers: 8

sourceDS: !!org.apache.commons.dbcp2.BasicDataSource
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/origin?autoReconnect=true&cacheServerConfiguration=true&useLocalSessionState=true&elideSetAutoCommits=true&connectTimeout=3000&socketTimeout=60000&useSSL=false&useAffectedRows=false&cacheCallableStmts=true&noAccessToProcedureBodies=true&characterEncoding=utf8&characterSetResults=utf8&connectionCollation=utf8_bin
  username: origin
  password: origin

targetDS: !!org.apache.commons.dbcp2.BasicDataSource
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/shard?autoReconnect=true&rewriteBatchedStatements=true&cacheServerConfiguration=true&useLocalSessionState=true&elideSetAutoCommits=true&connectTimeout=3000&socketTimeout=60000&useSSL=false&useAffectedRows=false&cacheCallableStmts=true&noAccessToProcedureBodies=true&characterEncoding=utf8&characterSetResults=utf8&connectionCollation=utf8_bin
  username: shard
  password: shard
  maxTotal: 30
  maxWaitMillis: 100
  validationQuery: SELECT 1
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis : 1200000
  numTestsPerEvictionRun : 10

retryCount: 10
retryMili: 5000
insertBatchCount: 100
insertIgnore: false

exportQuery: "select * from uldra where 1 = 1"
idGenerator:
  className: "net.gywn.algorithm.IDGeneratorHandlerImpl"
  params: ["dttm"]
  columnName: "guid"
rowModifier:
  className: "net.gywn.algorithm.RowModifierHandlerImpl"
  properties:
    param1: "param1"
    param2: "param2"
upsert: true
targetTables:
- name: "uldra"
  deleteQuery: "delete from uldra limit 10000"
- name: "uldra_part"
  columns: ["id", "name", "dttm"]
  deleteQuery: "delete from uldra_part limit 10000"