dataSources:
  ds0: !!org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql://127.0.0.1:3306/shard01?autoReconnect=true&cacheServerConfiguration=true&useLocalSessionState=true&elideSetAutoCommits=true&connectTimeout=3000&socketTimeout=60000&useSSL=false&useAffectedRows=true&cacheCallableStmts=true&noAccessToProcedureBodies=true&characterEncoding=utf8&characterSetResults=utf8&connectionCollation=utf8_bin
    username: shard
    password: shard
    maxTotal: 30
    maxWaitMillis: 100
    validationQuery: SELECT 1
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis : 1200000
    numTestsPerEvictionRun : 10
  ds1: !!org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql://127.0.0.1:3306/shard02?autoReconnect=true&cacheServerConfiguration=true&useLocalSessionState=true&elideSetAutoCommits=true&connectTimeout=3000&socketTimeout=60000&useSSL=false&useAffectedRows=true&cacheCallableStmts=true&noAccessToProcedureBodies=true&characterEncoding=utf8&characterSetResults=utf8&connectionCollation=utf8_bin
    username: shard
    password: shard
    maxTotal: 30
    maxWaitMillis: 100
    validationQuery: SELECT 1
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis : 1200000
    numTestsPerEvictionRun : 10

shardingRule:
  tables:
    uldra: 
      actualDataNodes: ds${0..1}.uldra
      databaseStrategy:
        standard:
          shardingColumn: id
          preciseAlgorithmClassName: net.gywn.algorithm.PreciseShardingCRC32
    uldra_part: 
      actualDataNodes: ds${0..1}.uldra_part
      databaseStrategy:
        standard:
          shardingColumn: id
          preciseAlgorithmClassName: net.gywn.algorithm.PreciseShardingCRC32
  bindingTables:
    - uldra, uldra_part
  defaultDataSourceName: ds0

props:
  sql.show: false